---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  project: argocd-project
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: {{ .Values.repository.targetRevision }}
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # https://argoproj.github.io/argo-cd/user-guide/auto_sync
  syncPolicy:
    automated: {}
